### ISSUE TITLE
First experience feedback

### ISSUE THREAD

**Issue by crayment** [Shopify/syrup#7]
Excited to stumble on this as I think there is demand for some GraphQL support libraries that are not Apollo. I just want type safe code generation for queries and mutations, not all the caching and observing stuff that come along with Apollo.

I tried to run this on my project but the errors I got were very unhelpful:

> ERROR: Syrup encountered an error
> The data couldn’t be read because it is missing.

So I tried running from Xcode but then it seems to be searching for files all relative to the build directory - which is deep in my derived data. I'm specifying absolute paths so not sure why it would do this and it's not clear to me how I could work around this.

**Comment by jaredh** [comment]
Thanks for giving syrup a try and appreciate the feedback! Totally agree the error messages can be significantly improved. 

I suspect this might be syrup having a problem reading the [Yaml configuration](https://github.com/Shopify/syrup#project-file-format). Would you mind sharing what that looks like? For reference, https://github.com/Shopify/syrup/blob/master/samples/swift/.syrup.yml is a good example of a basic valid config.

**Comment by crayment** [comment]
Sure! I have the following:

#### .syrup.yml
```yml
moduleName: MyProject
filenameSuffix: "generated"
header: |
        // Syrup auto-generated file
supportFilesHeader: |
        // Syrup auto-generated support file
accessLevelOverride: "internal" # optional field
generateSelections: true # optional field
```

#### .schema.yml
```yml
location: MyProject/API/GraphQL/schema.json
customScalars:
- graphType: DateTime
  nativeType: Date
```

And I'm running it from my shell via:

```shell
/Users/crayment/dev/play/syrup/.build/debug/Syrup generate MyProject/API/GraphQL/queries/ models support Syrup-Template
```

I copied the Swift template into my working dir as `Syrup-Template`. Initially I was referencing the path to my Syrup clone but that wasn't working either.

**Comment by crayment** [comment]
Trying with the exact yaml file you linked leads to:

> Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/crayment/dev/play/syrup/Sources/SyrupCore/Utilities/Loaders.swift, line 28
Illegal instruction: 4

I also tried to use the override option

```shell
/Users/crayment/dev/play/syrup/.build/debug/Syrup generate MyProject/API/GraphQL/queries/ models support Syrup-Template --override-schema MyProject/API/GraphQL/schema.json
```

But get the same error:

> The data couldn’t be read because it is missing.

**Comment by jaredh** [comment]
> Sure! I have the following:
> #### .syrup.yml
>
> ........... 
> 
> #### .schema.yml
> 
> I copied the Swift template into my working dir as `Syrup-Template`. Initially I was referencing the path to my Syrup clone but that wasn't working either.

Looks like your `.syrup.yml` config is incomplete and should contain the contents from your `.schema.yml` as well. You should be able to able to reference the language templates from your cloned Syrup repository too. 

Using the GitLab GraphQL schema from their introspection URL https://gist.github.com/jaredh/a4895c8c8f084b7fbce3b89571f91156 as an example, and the following `.syrup.yml`

```yml
location: gitlab.json
customScalars: []
moduleName: GitLab
header: |
        // Syrup auto-generated file
        import Foundation
supportFilesHeader: |
        // Syrup auto-generated support file
        import Foundation
generateSelections: false

```

```bash
$ ~/dev/syrup/.build/debug/Syrup generate graphql models support ~/dev/syrup/Templates/Swift
Loading schema: ./gitlab.json
Generating models
Parsing .graphql files
Writing to Responses
Writing to Queries
Writing to Mutations
Writing to Inputs
Writing to Enums
Writing to Fragments
Successfully wrote generated models to /Users/jared/gitlab/models
Generating support files
Successfully wrote generated support files to /Users/jared/gitlab/support
```

Breaking down the arguments I'm passing to `Syrup` are as follows,
`generate`: Option to generate both models and support files
 `graphql`: Folder which contains `*.graphql` operations
`models`: Folder where generated queries, reponses, enums, etc are written to
`support`: Folder where support files are written to
`~/dev/syrup/Templates/Swift`: Path to location of Swift templates

Maybe your schema is in an incorrect format or not specified correctly? 🤔
